name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Caso 1
      id: caso-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Caso 1
        setup-command: ''
        command: python classifica_triangulo.py
        input: 1 3 5
        expected-output: Não forma triângulo
        comparison-method: contains
        timeout: 5
    - name: Caso 2
      id: caso-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Caso 2
        setup-command: ''
        command: python classifica_triangulo.py
        input: 7 10 7
        expected-output: isósceles
        comparison-method: contains
        timeout: 5
    - name: Caso 3
      id: caso-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Caso 3
        setup-command: ''
        command: python classifica_triangulo.py
        input: 10 15 20
        expected-output: escaleno
        comparison-method: contains
        timeout: 5
    - name: Caso 4
      id: caso-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Caso 4
        setup-command: ''
        command: python classifica_triangulo.py
        input: 100 100 100
        expected-output: equilátero
        comparison-method: contains
        timeout: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CASO-1_RESULTS: "${{steps.caso-1.outputs.result}}"
        CASO-2_RESULTS: "${{steps.caso-2.outputs.result}}"
        CASO-3_RESULTS: "${{steps.caso-3.outputs.result}}"
        CASO-4_RESULTS: "${{steps.caso-4.outputs.result}}"
      with:
        runners: caso-1,caso-2,caso-3,caso-4
